# Generated by Django 4.2.20 on 2025-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_inn_partnerapplication_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplicationimage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_applications', to='app.partnerapplicationobject'),
        ),
    ]
