# Generated by Django 4.2.20 on 2025-05-16 07:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_useremail_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='obj_images/')),
                ('body', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='key',
            field=models.ImageField(upload_to='obj_images/'),
        ),
        migrations.AlterField(
            model_name='history',
            name='body',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('tashkent', 'TASHKENT'), ('bukhara', 'BUXORO'), ('samarqand', 'SAMARQAND'), ('fargona', 'FARGONA'), ('navoiy', 'NAVOIY'), ('andijon', 'ANDIJON'), ('namangan', 'NAMANGAN'), ('jizzax', 'JIZZAX'), ('sirdaryo', 'SIRDARYO'), ('surhandaryo', 'SURXANDARYO'), ('qashqadaryo', 'QASHQADARYO'), ('xorazm', 'XORAZM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='app.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='body',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='UserLoc',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to='app.user'),
        ),
    ]
