# Generated by Django 4.2.20 on 2025-04-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_partnerapplicationimage_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplicationimage',
            name='file',
            field=models.FileField(upload_to='obj_images'),
        ),
    ]
