# Generated by Django 4.2.20 on 2025-04-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_partnerapplicationimage_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplicationObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='obj_images/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_applications', to='app.partnerapplication')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('tashkent', 'TASHKENT'), ('buxoro', 'BUXORO'), ('samarqand', 'SAMARQAND'), ('fargona', 'FARGONA'), ('navoiy', 'NAVOIY'), ('andijon', 'ANDIJON'), ('namangan', 'NAMANGAN'), ('jizzax', 'JIZZAX'), ('sirdaryo', 'SIRDARYO'), ('surxandaryo', 'SURXANDARYO'), ('qashqadaryo', 'QASHQADARYO'), ('xorazm', 'XORAZM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_application_objects', to='app.location'),
        ),
        migrations.DeleteModel(
            name='PartnerApplicationImage',
        ),
    ]
