# Generated by Django 4.2.20 on 2025-04-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_partnerapplicationobjectimage_alter_location_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplicationobjectimage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_applications', to='app.partnerapplicationobject'),
        ),
    ]
