# Generated by Django 4.2.20 on 2025-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_branch_career_category_certificate_faq_feedback_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='obj_images/')),
                ('body', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='source',
            field=models.ImageField(upload_to='obj_images/'),
        ),
    ]
