# Generated by Django 4.2.20 on 2025-04-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_aboutus_history_alter_feedback_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderProduct', to='app.product'),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_application_objects', to='app.location'),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobjectimage',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_applications', to='app.partnerapplicationobject'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.category'),
        ),
        migrations.AlterField(
            model_name='userloc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userLoc', to='app.user'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancyApplication', to='app.vacancy'),
        ),
    ]
